# =============================================================================
# @file    test-actoin.yml
# @brief   GitHub Actions workflow to test Waystation
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file named LICENSE in the project directory
# @website https://github.com/caltechlibrary/waystation
#
# This workflow file was originally based on work by GitHub user "peaceiris":
# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-python
# =============================================================================

name: "Test Waystation"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  Workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: caltechlibrary/waystation@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        debug: true
